17.ASP.NET-MVC/99.ExamPrep/Source/Web/ForumSystem.Web/ViewModels/Questions/QuestionDisplayViewModel.cs
namespace ForumSystem.Web.ViewModels.Questions
{
    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure.Mapping;

    public class QuestionDisplayViewModel : IMapFrom<Post>
    {
        public string Title { get; set; }

        public string Content { get; set; }
    }
}

17.ASP.NET-MVC/99.ExamPrep/Source/Web/ForumSystem.Web/Controllers/QuestionsController.cs
namespace ForumSystem.Web.Controllers
{
    using System.Linq;
    using System.Web.Mvc;

    using AutoMapper.QueryableExtensions;

    using ForumSystem.Data.Common.Repository;
    using ForumSystem.Data.Models;
    using ForumSystem.Web.Infrastructure;
    using ForumSystem.Web.InputModels.Questions;
    using ForumSystem.Web.ViewModels.Questions;

    using Microsoft.AspNet.Identity;

    public class QuestionsController : Controller
    {
        private readonly IDeletableEntityRepository<Post> posts;

        private readonly ISanitizer sanitizer;

        public QuestionsController(IDeletableEntityRepository<Post> posts, ISanitizer sanitizer)
        {
            this.posts = posts;
            this.sanitizer = sanitizer;
        }

        // /questions/26864653/mysql-workbench-crash-on-start-on-windows
        public ActionResult Display(int id, string url, int page = 1)
        {
            var postViewModel = this.posts.All().Where(x => x.Id == id)
                .Project().To<QuestionDisplayViewModel>().FirstOrDefault();

            if (postViewModel == null)
            {
                return this.HttpNotFound("No such post");
            }

            return this.View(postViewModel);
        }

        // /questions/tagged/javascript
        public ActionResult GetByTag(string tag)
        {
            return this.Content(tag);
        }

        [HttpGet]
        [Authorize]
        public ActionResult Ask()
        {
            var model = new AskInputModel();
            return this.View(model);
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public ActionResult Ask(AskInputModel input)
        {
            if (ModelState.IsValid)
            {
                var userId = this.User.Identity.GetUserId();

                var post = new Post
                    {
                        Title = input.Title,
                        Content = this.sanitizer.Sanitize(input.Content),
                        AuthorId = userId,
                        
                        // TODO: Tags
                        // TODO: Author
                    };

                this.posts.Add(post);
                this.posts.SaveChanges();
                return this.RedirectToAction("Display", new { id = post.Id, url = "new" });
            }

            return this.View(input);
        }
    }
}

17.ASP.NET-MVC/99.ExamPrep/Source/Web/ForumSystem.Web/Views/Questions/Ask.cshtml
@model ForumSystem.Web.InputModels.Questions.AskInputModel
@{
    ViewBag.Title = "Ask question";
}

<h1>@ViewBag.Title</h1>
@using (Html.BeginForm("Ask", "Questions", FormMethod.Post, new { @class = "form-horizontal" }))
{
    @Html.AntiForgeryToken()

    @Html.ValidationSummary("", new { @class = "text-danger" })
    
    <div class="form-group">
        @Html.LabelFor(model => model.Title, new { @class = "col-md-1 control-label" })
        <div class="col-md-11">
            @Html.EditorFor(model => model.Title, new { placeholder = "Title123" })
        </div>
    </div>

    <div class="form-group">
        @Html.EditorFor(model => model.Content)
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Tags, new { @class = "col-md-1 control-label" })
        <div class="col-md-11">
            @Html.EditorFor(model => model.Tags, new { placeholder = "at least one tag such as (ruby-on-rails-3 python c), max 5 tags separated by comma" })
        </div>
    </div>
    
    <div class="form-group text-center">
        <input type="submit" value="Ask question" class="btn btn-primary btn-lg" />
    </div>
}

17.ASP.NET-MVC/99.ExamPrep/Source/Web/ForumSystem.Web/Views/Questions/Display.cshtml
@model ForumSystem.Web.ViewModels.Questions.QuestionDisplayViewModel
@{
    ViewBag.Title = Model.Title;
}

<h1>@ViewBag.Title</h1>
@Html.Raw(Model.Content)